app:
  replicas: 3
  customCommand: []
  customArgs: []
  env: []
  resources: {}

podAnnotations: {}
podLabels: {}

probes:
  readiness: {}
  liveness: {}

service:
  enabled: false
  port: 8080

rbac:
  enabled: false
  roleBinding:
    autoCreate: true
    additionalRoles: []
    additionalClusterRoles: []
  clusterRoleBinding:
    clusterRoles: []

applicationYamlConfig: {}
  # name: configmap
# value: |

applicationYamlSecret: {}
  # name: secret
# value: |

ingress:
  enabled: false
  className: nginx
  host: ""
  path: ""
  pathType: Prefix