app:
  name: coffeeorderservice
  image: seojeonghyeon0630/coffeeorderservice:0.0.1
  port: 8080
  replicas: 3
  customCommand: []
  customArgs: []
  env: []
  resources: {}
  labels:
    layer: backend
    environment: dev
    version: 0.0.1
    release: blue

podAnnotations:
  app.version: "0.0.1"
  app.build: "Gradle Kotlin"
  environment: "dev"
  monitoring.enabled: "false"
  monitoring.tool: ""
  log-config: "info"
  deployment.pipeline: "develop"

podLabels: {}
podImagePullPolicy: Always
podVolumeMounts:
  enabled: true
  name: logfile-data
  mountPath: "/output/$(HOSTNAME)"
podVolumes:
  enabled: true
  name: logfile-data
  persistentVolumeClaimName: logstorage-pvc
  storage: 10Gi
podPersistentVolume:
  name: logstorage-pv
  pdName: logstorage

probes:
  readiness:
    httpGet:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  liveness:
    httpGet:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3

service:
  enabled: true
  port: 80

rbac:
  enabled: true
  roleBinding:
    autoCreate: true
    additionalRoles: []
    additionalClusterRoles: []
  clusterRoleBinding:
    clusterRoles: []

applicationYamlConfig: {}
  # name: configmap
# value: |

applicationYamlSecret: {}
  # name: secret
# value: |

ingress:
  enabled: false
  className: nginx
  host: ""
  path: ""
  pathType: Prefix