apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}

    {{- with .Values.app.labels}}
      {{- toYaml .layer | nindent 4}}
      {{- toYaml .environment | nindent 4}}
      {{- toYaml .version | nindent 4}}
      {{- toYaml .release | nindent 4}}
    {{- end}}
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      {{- with .Values.app.labels}}
        {{- toYaml .layer | nindent 6}}
        {{- toYaml .environment | nindent 6}}
        {{- toYaml .version | nindent 6}}
        {{- toYaml .environment | nindent 6}}
      {{- end}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.name }}
        {{- with .Values.app.labels}}
          {{- toYaml . | nindent 8}}
        {{- end}}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Values.app.name }}
      {{- end }}
      containers:
        - image: {{ .Values.app.image }}
          name: {{ .Values.app.name }}
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.app.port }}

          imagePullPolicy: {{ .Values.podImagePullPolicy}}

          {{- if .Values.podVolumeMounts.enabled}}
          volumeMounts:
            - mountPath: {{ .Values.podVolumeMounts.mountPath }}
              name: {{ .Values.podVolumeMounts.name }}
          {{- end}}

          {{- with .Values.app.customCommand }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.app.customArgs }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.app.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- if .Values.podVolumes.enabled}}
      volumes:
        - name: {{ .Values.podVolumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.podVolumes.persistentVolumeClaimName }}
      {{- end}}