{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    {{- with .Values.app.labels}}
    layer: {{- toYaml .layer | nindent 6}}
    environment: {{- toYaml .environment | nindent 6}}
    version: {{- toYaml .version | nindent 6}}
    release: {{- toYaml .release | nindent 6}}
    {{- end}}
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}
    {{- with .Values.app.labels}}
    layer: {{- toYaml .layer | nindent 6}}
    environment: {{- toYaml .environment | nindent 6}}
    version: {{- toYaml .version | nindent 6}}
    release: {{- toYaml .release | nindent 6}}
    {{- end}}
{{- end }}