{{- if .Values.podVolumes.enabled}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.podPersistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.podVolumes.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: {{ .Values.podPersistentVolume.pdName }}
    fsType: ext4
{{- end }}