apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.app.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccount: {{ .Values.app.name }}
      {{- end }}
      containers:
        - image: {{ .Values.app.image }}
          name: {{ .Values.app.name }}
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.app.port }}
          {{- with .Values.app.customCommand }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.app.customArgs }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.app.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 10 }}
          {{- end }}