{{- if eq .Values.app.profiles "dev" }}

{{- if .Values.postgres.standAloneMode.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.standAlone.name }}
spec:
  serviceName: {{ .Values.postgres.standAlone.name }}
  replicas: {{ .Values.postgres.standAlone.replicas }}
  selector:
    matchLabels:
      {{- with .Values.postgres.standAlone.labels }}
      app: {{- toYaml .app | nindent 8 }}
      layer: {{- toYaml .layer | nindent 8 }}
      role: {{- toYaml .role | nindent 8 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.postgres.standAlone.labels }}
        app: {{- toYaml .app | nindent 10 }}
        layer: {{- toYaml .layer | nindent 10 }}
        role: {{- toYaml .role | nindent 10 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.postgres.standAlone.appName }}
          image: {{ .Values.postgres.standAlone.image }}
          env:
            {{- with .Values.postgres.standAlone.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.postgres.standAlone.ports.containerPort}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.standAlone.name }}
spec:
  selector:
    app: {{ .Values.postgres.standAlone.name }}
    {{- with .Values.postgres.standAlone.labels }}
    layer: {{- toYaml .layer | nindent 8 }}
    role: {{- toYaml .role | nindent 8 }}
    {{- end }}
  ports:
    - protocol: {{ .Values.postgres.standAlone.ports.protocol}}
      port: {{ .Values.postgres.standAlone.ports.containerPort}}
      targetPort: {{ .Values.postgres.standAlone.ports.containerPort}}


{{- end }}
{{- end }}