spring:
  messages:
    basename: messages, errors
  security:
    jwt:
      header: Authorization
      secret: SnVzdGluU2VvLVRlYW9yZGVyc2VydmljZS1TcHJpbmdCb290LUpXVC1TZWNyZXQtVG9rZW4=
      token_expiration_time: 864000
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:teaorderdb;
  h2:
    console:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: on_param
    include-stacktrace: on_param
    include-message: on_param
    include-exception: true

order:
  pay-status:
    pending: "PENDING"
    confirmed: "CONFIRMED"
    canceled: "CANCELED"
    rejected: "REJECTED"
    completed: "COMPLETED"

