spring:
  config:
    activate:
      on-profile: stg
  security:
    jwt:
      header: Authorization
      secret: SnVzdGluU2VvLVRlYW9yZGVyc2VydmljZS1TcHJpbmdCb290LUpXVC1TZWNyZXQtVG9rZW4=
      token_expiration_time: 864000
  datasource:
    driver-class-name: org.postgresql.Driver
    username: api_user
    password: '00000000'
    url: jdbc:postgresql://localhost:5432/teaorderdb
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: seojeonghyeon0630@gmail.com
    password: qwcwnodicfohbtnf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          enable: true
          starttls:
            enable: true

server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: info
  file:
    path: /output/${HOSTNAME}
app:
  host: http://localhost:8080
management:
  endpoint:
    health:
      enabled: true
      show-details: always